---
title: "Case I: Weibull Distribution"
font size: 12pt
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{multicol}
- \usepackage{multirow}
- \usepackage{leading}
- \leading{15 pt}
output: pdf_document
classoption: landscape
---

# ARL Table for shape parameter increase from the in-control value in $\textbf{Wei(1.1,1.6)}$    


```{r, echo=FALSE , warning=FALSE}
library(knitr)
library(kableExtra)

arl_wei_alpha_pos<-data.frame(readRDS("ARL_wei_alpha_Pos.RDs"))
rownames(arl_wei_alpha_pos)<-NULL
alpha<-c(1,1.05,1.1,1.15)
mean<- c(1.60,1.57,1.54,1.52)
arl_wei_alpha_pos<-cbind(alpha,mean,arl_wei_alpha_pos)
rownames(arl_wei_alpha_pos)<-NULL
colnames(arl_wei_alpha_pos)[1]<-"$\\alpha$"
colnames(arl_wei_alpha_pos)[2] <- "$\\mu_X$"
colnames(arl_wei_alpha_pos)[3] <- "$ARL$"
colnames(arl_wei_alpha_pos)[4] <- "$ARL^+$"
colnames(arl_wei_alpha_pos)[5] <- "$ARL$"
colnames(arl_wei_alpha_pos)[6] <- "$ARL^+$"
colnames(arl_wei_alpha_pos)[7] <- "$ARL$"
colnames(arl_wei_alpha_pos)[8] <- "$ARL^+$"
colnames(arl_wei_alpha_pos)[9] <- "$ARL$"
colnames(arl_wei_alpha_pos)[10] <- "$ARL^+$"
colnames(arl_wei_alpha_pos)[11] <- "$ARL$"
colnames(arl_wei_alpha_pos)[12] <- "$ARL^+$"
colnames(arl_wei_alpha_pos)[13] <- "$ARL$"
colnames(arl_wei_alpha_pos)[14] <- "$ARL^+$"

kable(arl_wei_alpha_pos,"latex",digits = 2, escape = FALSE) %>%
  kable_styling(latex_option = c("HOLD_position"), position = "left") %>%
  add_header_above(c("","","$\\\\bar{X}$ chart" = 2, "$\\\\tilde{X}$ chart"= 2, "$\\\\bar{X}$ chart" = 2, "$\\\\tilde{X}$ chart"= 2,"$\\\\bar{X}$ chart" = 2, "$\\\\tilde{X}$ chart"= 2),escape = FALSE) %>%
  add_header_above(c("","","$n=5$"=4, "$n=10$"=4, "$n=20$"=4),escape = FALSE) %>%
  column_spec(1:2, bold = TRUE)

```   



# ARL Table for scale parameter increase from the in-control value in $\textbf{Wei(1.1,1.6)}$


```{r, echo=FALSE , warning=FALSE}
library(knitr)
library(kableExtra)

arl_wei_beta_pos<-data.frame(readRDS("ARL_wei_beta_pos.RDs"))
rownames(arl_wei_beta_pos)<-NULL
beta<-c(1.6,1.8,2.0,2.2,2.4,2.6)
mean<- c(1.6,1.8,2.0,2.2,2.4,2.6)
arl_wei_beta_pos<-cbind(beta,mean,arl_wei_beta_pos)
rownames(arl_wei_beta_pos)<-NULL
colnames(arl_wei_beta_pos)[1]<-"$\\beta$"
colnames(arl_wei_beta_pos)[2] <- "$\\mu_X$"
colnames(arl_wei_beta_pos)[3] <- "$ARL$"
colnames(arl_wei_beta_pos)[4] <- "$ARL^+$"
colnames(arl_wei_beta_pos)[5] <- "$ARL$"
colnames(arl_wei_beta_pos)[6] <- "$ARL^+$"
colnames(arl_wei_beta_pos)[7] <- "$ARL$"
colnames(arl_wei_beta_pos)[8] <- "$ARL^+$"
colnames(arl_wei_beta_pos)[9] <- "$ARL$"
colnames(arl_wei_beta_pos)[10] <- "$ARL^+$"
colnames(arl_wei_beta_pos)[11] <- "$ARL$"
colnames(arl_wei_beta_pos)[12] <- "$ARL^+$"
colnames(arl_wei_beta_pos)[13] <- "$ARL$"
colnames(arl_wei_beta_pos)[14] <- "$ARL^+$"

kable(arl_wei_beta_pos,"latex",digits = 2, escape = FALSE) %>%
  kable_styling(latex_option = c("HOLD_position"), position = "left") %>%
  add_header_above(c("","","$\\\\bar{X}$ chart" = 2, "$\\\\tilde{X}$ chart"= 2, "$\\\\bar{X}$ chart" = 2, "$\\\\tilde{X}$ chart"= 2,"$\\\\bar{X}$ chart" = 2, "$\\\\tilde{X}$ chart"= 2),escape = FALSE) %>%
  add_header_above(c("","","$n=5$"=4, "$n=10$"=4, "$n=20$"=4),escape = FALSE) %>%
  column_spec(1:2, bold = TRUE)
```